### ISSUE TITLE
Model E2 Not Detect

### ISSUE THREAD

**Issue by RupeshVM** [mariorojas/MorphoMSO#1]
Morpho Model MSO 1300 E2 not detect. Please help me

**Comment by mariorojas** [comment]
Hi @rupvm , this project is created only for tablets with a MorphoSmart 1300 reader implemented, are you running the app in this kind of environment?

**Comment by RupeshVM** [comment]
Actually, I am running this code on nougat device. It says device not
detected, usb permission required. I have morpho 1300 E2 device. I will try
on tablet.
